version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
  maintenance:
    uploadpurging:
      enabled: true
      age: 1h
      interval: 1h
      dryrun: false
http:
  addr: :5000
health:
  storagedriver:
    enabled: true
    interval: 10s
threshold: 3